// VinaLex — Mock Data (dùng khi Backend chưa sẵn sàng)
import { Procedure, Category } from '@/types';

export const CATEGORIES: Category[] = [
  { id: '1', slug: 'dat-dai', label: 'Đất đai & Nhà ở', icon: '🏠', count: 50, color: '#4F7FFA' },
  { id: '2', slug: 'ho-tich', label: 'Hộ tịch', icon: '👨‍👩‍👧', count: 39, color: '#06B6D4' },
  { id: '3', slug: 'doanh-nghiep', label: 'Doanh nghiệp', icon: '🏢', count: 19, color: '#8B5CF6' },
  { id: '4', slug: 'giao-thong', label: 'Giao thông', icon: '🚗', count: 10, color: '#F59E0B' },
  { id: '5', slug: 'giao-duc', label: 'Giáo dục', icon: '📚', count: 13, color: '#10B981' },
  { id: '6', slug: 'y-te', label: 'Y tế', icon: '🏥', count: 24, color: '#EF4444' },
  { id: '7', slug: 'thue', label: 'Thuế & Tài chính', icon: '💰', count: 55, color: '#EC4899' },
  { id: '8', slug: 'lao-dong', label: 'Lao động - BHXH', icon: '👷', count: 58, color: '#14B8A6' },
];

export const MOCK_PROCEDURES: Procedure[] = [
  {
    id: '1',
    slug: 'cap-giay-chung-nhan-quyen-su-dung-dat',
    title: 'Cấp giấy chứng nhận quyền sử dụng đất lần đầu',
    category: 'Đất đai & Nhà ở',
    categorySlug: 'dat-dai',
    description: 'Thủ tục cấp giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà ở và tài sản khác gắn liền với đất cho hộ gia đình, cá nhân lần đầu.',
    steps: [
      { index: 1, title: 'Chuẩn bị hồ sơ', description: 'Thu thập đầy đủ giấy tờ theo danh sách quy định', duration: '1-3 ngày' },
      { index: 2, title: 'Nộp hồ sơ', description: 'Nộp tại Bộ phận một cửa UBND cấp huyện hoặc văn phòng đăng ký đất đai', duration: '1 ngày' },
      { index: 3, title: 'Thẩm tra hồ sơ', description: 'Cán bộ địa chính kiểm tra tính hợp lệ của hồ sơ', duration: '5-10 ngày' },
      { index: 4, title: 'Đo đạc thực địa', description: 'Đơn vị đo đạc tiến hành đo đạc tại thực địa (nếu cần)', duration: '3-7 ngày' },
      { index: 5, title: 'Cấp giấy chứng nhận', description: 'Nhận kết quả và ký vào sổ cấp', duration: '1 ngày' },
    ],
    documents: [
      'Đơn đăng ký cấp Giấy chứng nhận (Mẫu 04/ĐK)',
      'Chứng minh nhân dân / CCCD của chủ sử dụng',
      'Giấy tờ về quyền sử dụng đất (nếu có)',
      'Trích lục bản đồ địa chính thửa đất',
      'Giấy tờ chứng minh nguồn gốc đất',
    ],
    processingTime: '30 ngày làm việc',
    fee: '100.000 - 500.000 VNĐ',
    agency: 'Văn phòng Đăng ký đất đai',
    level: 'Quận/Huyện',
    tags: ['Sổ đỏ', 'Đất đai', 'GCNQSDĐ'],
    updatedAt: '2024-06-01',
    viewCount: 12540,
  },
  {
    id: '2',
    slug: 'dang-ky-khai-sinh',
    title: 'Đăng ký khai sinh cho trẻ em (Làm giấy khai sinh)',
    category: 'Hộ tịch',
    categorySlug: 'ho-tich',
    description: 'Thủ tục đăng ký khai sinh, làm giấy khai sinh cho trẻ em mới sinh tại Việt Nam, do UBND cấp xã/phường nơi cư trú của người cha hoặc người mẹ thụ lý và cấp Giấy khai sinh.',
    steps: [
      { index: 1, title: 'Chuẩn bị hồ sơ khai sinh', description: 'Chuẩn bị Giấy chứng sinh từ cơ sở y tế và CCCD/Hộ chiếu của cha, mẹ', duration: 'Trong ngày' },
      { index: 2, title: 'Nộp hồ sơ trực tiếp hoặc trực tuyến', description: 'Nộp tại Bộ phận một cửa UBND cấp xã/phường hoặc nộp qua Cổng Dịch vụ công quốc gia (dichvucong.gov.vn)', duration: '1 ngày' },
      { index: 3, title: 'Thẩm tra và ghi vào Sổ hộ tịch', description: 'Công chức tư pháp - hộ tịch kiểm tra hồ sơ, ghi nội dung vào Sổ đăng ký khai sinh', duration: 'Trong ngày làm việc' },
      { index: 4, title: 'Nhận Giấy khai sinh gốc', description: 'Chủ tịch UBND cấp xã ký và cấp Giấy khai sinh bản chính cho người yêu cầu', duration: '1 ngày' },
    ],
    documents: [
      'Tờ khai đăng ký khai sinh (theo mẫu quy định)',
      'Giấy chứng sinh do bệnh viện hoặc cơ sở y tế cấp',
      'Căn cước công dân hoặc Hộ chiếu của cha, mẹ hoặc người đi khai sinh',
      'Giấy chứng nhận kết hôn của cha mẹ (nếu có)',
      'Văn bản ủy quyền (nếu người đi khai sinh không phải cha, mẹ)',
    ],
    processingTime: 'Trong ngày làm việc (tối đa 3 ngày)',
    fee: 'Miễn phí đăng ký đúng hạn',
    agency: 'Ủy ban nhân dân Phường/Xã/Thị trấn',
    level: 'Phường/Xã',
    tags: ['Làm giấy khai sinh', 'Đăng ký khai sinh', 'Giấy khai sinh', 'Khai sinh', 'Hộ tịch', 'Trẻ em', 'UBND'],
    updatedAt: '2024-06-20',
    viewCount: 18520,
  },
  {
    id: '3',
    slug: 'dang-ky-thanh-lap-cong-ty-tnhh',
    title: 'Đăng ký thành lập Công ty TNHH một thành viên',
    category: 'Doanh nghiệp',
    categorySlug: 'doanh-nghiep',
    description: 'Thủ tục đăng ký thành lập doanh nghiệp theo loại hình Công ty TNHH một thành viên tại Phòng Đăng ký kinh doanh - Sở KH&ĐT.',
    steps: [
      { index: 1, title: 'Chuẩn bị hồ sơ', description: 'Soạn thảo Điều lệ công ty, danh sách thành viên', duration: '2-3 ngày' },
      { index: 2, title: 'Đăng ký qua Cổng thông tin quốc gia', description: 'Nộp hồ sơ tại dangkykinhdoanh.gov.vn', duration: '1 ngày' },
      { index: 3, title: 'Thẩm định hồ sơ', description: 'Phòng ĐKKD xem xét hồ sơ', duration: '3 ngày' },
      { index: 4, title: 'Nhận Giấy chứng nhận ĐKDN', description: 'Nhận kết quả và khắc con dấu', duration: '1 ngày' },
    ],
    documents: [
      'Giấy đề nghị đăng ký doanh nghiệp',
      'Điều lệ công ty',
      'CCCD của chủ sở hữu công ty',
      'Văn bản ủy quyền (nếu nộp qua người đại diện)',
    ],
    processingTime: '3 ngày làm việc',
    fee: '50.000 VNĐ',
    agency: 'Sở Kế hoạch và Đầu tư',
    level: 'Tỉnh/TP',
    tags: ['Doanh nghiệp', 'TNHH', 'Thành lập công ty'],
    updatedAt: '2024-06-10',
    viewCount: 7320,
  },
  {
    id: '4',
    slug: 'cap-bang-lai-xe-b1',
    title: 'Cấp giấy phép lái xe hạng B1',
    category: 'Giao thông',
    categorySlug: 'giao-thong',
    description: 'Thủ tục thi và cấp giấy phép lái xe hạng B1 (xe ô tô dưới 9 chỗ ngồi, không hành nghề lái xe) tại các Sở GTVT hoặc cơ sở đào tạo được cấp phép.',
    steps: [
      { index: 1, title: 'Đăng ký học & thi', description: 'Đăng ký tại cơ sở đào tạo lái xe được cấp phép', duration: '1 ngày' },
      { index: 2, title: 'Học lý thuyết', description: 'Hoàn thành ít nhất 90 giờ học lý thuyết', duration: '1 tháng' },
      { index: 3, title: 'Học thực hành', description: 'Hoàn thành ít nhất 420 km thực hành', duration: '2-3 tháng' },
      { index: 4, title: 'Thi sát hạch', description: 'Thi lý thuyết và thực hành lái xe', duration: '1 ngày' },
      { index: 5, title: 'Nhận bằng lái', description: 'Nhận giấy phép lái xe tại Sở GTVT', duration: '5-7 ngày' },
    ],
    documents: [
      'CCCD hoặc hộ chiếu còn hạn',
      'Giấy khám sức khỏe (theo Mẫu BV2)',
      'Ảnh 3x4 nền trắng (6 ảnh)',
      'Sổ hộ khẩu hoặc KT3 (để xác nhận cư trú)',
    ],
    processingTime: '3-6 tháng',
    fee: '3.000.000 - 5.000.000 VNĐ',
    agency: 'Sở Giao thông Vận tải',
    level: 'Tỉnh/TP',
    tags: ['Bằng lái xe', 'B1', 'GPLX'],
    updatedAt: '2024-04-20',
    viewCount: 15680,
  },
  {
    id: '5',
    slug: 'dang-ky-tam-tru',
    title: 'Đăng ký tạm trú',
    category: 'Hộ tịch',
    categorySlug: 'ho-tich',
    description: 'Thủ tục đăng ký tạm trú cho công dân Việt Nam khi lưu trú tại địa phương khác nơi đăng ký hộ khẩu thường trú từ 30 ngày trở lên.',
    steps: [
      { index: 1, title: 'Chuẩn bị hồ sơ', description: 'Điền tờ khai đăng ký tạm trú', duration: '30 phút' },
      { index: 2, title: 'Nộp hồ sơ', description: 'Nộp tại Công an phường/xã nơi tạm trú', duration: '1 ngày' },
      { index: 3, title: 'Nhận kết quả', description: 'Nhận sổ tạm trú', duration: '1-3 ngày' },
    ],
    documents: [
      'Tờ khai thay đổi thông tin cư trú (theo Mẫu CT01)',
      'CCCD hoặc hộ chiếu',
      'Giấy tờ chứng minh chỗ ở hợp pháp (hợp đồng thuê nhà...)',
    ],
    processingTime: '3 ngày làm việc',
    fee: 'Miễn phí',
    agency: 'Công an Phường/Xã',
    level: 'Phường/Xã',
    tags: ['Tạm trú', 'Hộ khẩu', 'Cư trú'],
    updatedAt: '2024-05-01',
    viewCount: 11200,
  },
  {
    id: '6',
    slug: 'quyet-toan-thue-tncn',
    title: 'Quyết toán thuế thu nhập cá nhân',
    category: 'Thuế & Tài chính',
    categorySlug: 'thue',
    description: 'Thủ tục quyết toán thuế TNCN hàng năm cho cá nhân có thu nhập từ tiền lương, tiền công, qua ứng dụng iCanhan hoặc nộp trực tiếp tại cơ quan thuế.',
    steps: [
      { index: 1, title: 'Tổng hợp thu nhập', description: 'Thu thập chứng từ khấu trừ thuế từ tất cả nguồn thu', duration: '1-2 ngày' },
      { index: 2, title: 'Khai quyết toán online', description: 'Đăng nhập thuedientu.gdt.gov.vn và điền tờ khai', duration: '1 ngày' },
      { index: 3, title: 'Nộp thuế hoặc hoàn thuế', description: 'Nộp số thuế còn thiếu hoặc yêu cầu hoàn thuế', duration: '1-30 ngày' },
    ],
    documents: [
      'Tờ khai quyết toán thuế TNCN (Mẫu 02/QTT-TNCN)',
      'Chứng từ khấu trừ thuế TNCN',
      'Giấy tờ chứng minh người phụ thuộc (nếu có)',
      'Hóa đơn bảo hiểm nhân thọ, từ thiện... (nếu có)',
    ],
    processingTime: '1-3 ngày (online)',
    fee: 'Miễn phí',
    agency: 'Cục Thuế / Chi cục Thuế',
    level: 'Quận/Huyện',
    tags: ['Thuế TNCN', 'Quyết toán', 'Hoàn thuế'],
    updatedAt: '2024-06-15',
    viewCount: 8900,
  },
  {
    id: '7',
    slug: 'cap-ban-sao-trich-luc-khai-sinh',
    title: 'Cấp bản sao trích lục khai sinh (Làm lại / Cấp lại giấy khai sinh)',
    category: 'Hộ tịch',
    categorySlug: 'ho-tich',
    description: 'Thủ tục cấp bản sao trích lục khai sinh khi bị mất, rách nát hoặc cần bổ sung hồ sơ giấy tờ, nộp tại cơ quan quản lý hộ tịch bất kỳ trên toàn quốc.',
    steps: [
      { index: 1, title: 'Chuẩn bị tờ khai', description: 'Điền tờ khai cấp bản sao trích lục hộ tịch', duration: '15 phút' },
      { index: 2, title: 'Nộp hồ sơ trực tiếp hoặc trực tuyến', description: 'Nộp tại UBND cấp xã hoặc nộp qua Cổng dịch vụ công quốc gia', duration: '1 ngày' },
      { index: 3, title: 'Nhận bản sao trích lục', description: 'Cơ quan hộ tịch tra cứu cơ sở dữ liệu và in cấp trích lục', duration: 'Trong ngày làm việc' },
    ],
    documents: [
      'Tờ khai cấp bản sao trích lục hộ tịch',
      'CCCD/Hộ chiếu người yêu cầu',
      'Giấy tờ chứng minh quan hệ nhân thân (nếu được ủy quyền)',
    ],
    processingTime: 'Trong ngày làm việc',
    fee: '8.000 VNĐ / bản sao',
    agency: 'UBND Phường/Xã hoặc Trung tâm phục vụ HCC',
    level: 'Phường/Xã',
    tags: ['Làm lại giấy khai sinh', 'Cấp lại giấy khai sinh', 'Trích lục khai sinh', 'Giấy khai sinh', 'Khai sinh', 'Hộ tịch'],
    updatedAt: '2024-06-18',
    viewCount: 14200,
  },
  {
    id: '8',
    slug: 'cap-the-can-cuoc',
    title: 'Cấp thẻ Căn cước công dân gắn chip (Làm thẻ Căn cước / CCCD)',
    category: 'Hộ tịch',
    categorySlug: 'ho-tich',
    description: 'Thủ tục cấp thẻ Căn cước cho công dân từ đủ 14 tuổi hoặc trẻ em dưới 14 tuổi theo Luật Căn cước mới nhất.',
    steps: [
      { index: 1, title: 'Đăng ký hẹn lịch', description: 'Đăng ký qua VNeID hoặc đến trực tiếp cơ quan Công an', duration: '1 ngày' },
      { index: 2, title: 'Thu nhận thông tin', description: 'Chụp ảnh chân dung, thu nhận vân tay và mống mắt', duration: '15 phút' },
      { index: 3, title: 'Nhận thẻ Căn cước', description: 'Nhận trực tiếp hoặc chuyển phát bưu chính về tận nhà', duration: '7 ngày làm việc' },
    ],
    documents: [
      'Thông tin định danh trên VNeID',
      'Thẻ CCCD/CMND cũ (nếu có để thu hồi)',
      'Giấy khai sinh (đối với trẻ em dưới 14 tuổi)',
    ],
    processingTime: '7 ngày làm việc',
    fee: 'Miễn phí lần đầu / 30.000 - 50.000 VNĐ cấp đổi',
    agency: 'Công an Quận/Huyện/Thị xã',
    level: 'Quận/Huyện',
    tags: ['Làm căn cước', 'Căn cước công dân', 'CCCD', 'Làm thẻ căn cước', 'Định danh', 'VNeID'],
    updatedAt: '2024-07-01',
    viewCount: 25300,
  },
  {
    id: '9',
    slug: 'dang-ky-ket-hon',
    title: 'Đăng ký kết hôn trong nước',
    category: 'Hộ tịch',
    categorySlug: 'ho-tich',
    description: 'Thủ tục đăng ký kết hôn giữa hai công dân Việt Nam cư trú tại Việt Nam tại UBND cấp xã.',
    steps: [
      { index: 1, title: 'Chuẩn bị tờ khai', description: 'Hai bên nam nữ điền tờ khai đăng ký kết hôn', duration: '1 ngày' },
      { index: 2, title: 'Nộp hồ sơ trực tiếp', description: 'Cả hai bên có mặt tại UBND cấp xã nơi cư trú của một trong hai bên', duration: '1 ngày' },
      { index: 3, title: 'Ký và trao Giấy chứng nhận', description: 'Hai bên cùng ký vào Sổ hộ tịch và Giấy chứng nhận kết hôn', duration: 'Trong ngày làm việc' },
    ],
    documents: [
      'Tờ khai đăng ký kết hôn (theo mẫu)',
      'CCCD hoặc Hộ chiếu của hai bên nam, nữ',
      'Giấy xác nhận tình trạng hôn nhân (nếu cư trú khác địa bàn)',
    ],
    processingTime: 'Trong ngày làm việc',
    fee: 'Miễn phí',
    agency: 'Ủy ban nhân dân Phường/Xã/Thị trấn',
    level: 'Phường/Xã',
    tags: ['Đăng ký kết hôn', 'Kết hôn', 'Hộ tịch', 'Giấy kết hôn'],
    updatedAt: '2024-06-12',
    viewCount: 16890,
  },
];

export const STATS = [
  { label: 'Thủ tục hành chính', value: '550+', icon: '📋' },
  { label: 'Văn bản pháp luật', value: '200+', icon: '⚖️' },
  { label: 'Điều khoản pháp lý số hóa', value: '8,300+', icon: '📚' },
  { label: 'Chuẩn hóa thể thức hành chính', value: '100%', icon: '🛡️' },
];
